---
title: "R Notebook"
output: html_notebook
---



deicde on flex v shiny dashboard -- shny would be best but more $$$$?


```{r load data}
# ADDING TEST
# load data
library(medicaldata)

library(tidyverse)
library("kableExtra")

# this one looks good!
indo_rct <- medicaldata::indo_rct

```

# codebook
https://htmlpreview.github.io/?https://github.com/higgi13425/medicaldata/blob/master/man/codebooks/indo_rct_codebook.html

```{r}
# codebook
# https://htmlpreview.github.io/?https://github.com/higgi13425/medicaldata/blob/master/man/codebooks/indo_rct_codebook.html


#article related
#https://www.nejm.org/doi/full/10.1056/NEJMoa1111103



```


```{r}

head(indo_rct)

```



```{r}

indo_rct %>% group_by(bleed,rx) %>% count()

# all post pancreatitis 

primary_outcome <- indo_rct %>% 
                   group_by(outcome,rx) %>% count() %>% group_by(rx) %>%
                   mutate(percent = round(n/sum(n),3)) %>%
                   ungroup() %>%
                   filter(outcome == "1_yes") %>%
                   mutate(rx = ifelse(rx == "0_placebo","Placebo","Indomethacin"))

primary_outcome

ggplot(primary_outcome, aes(x = rx, y = percent, fill = rx)) +
       geom_col(width = 0.5, color = "black") +
       scale_y_continuous("Patients (%)",
                          labels = scales::percent,
                          expand = c(0,0), limits = c(0,0.2)) +
       scale_x_discrete("All Post-ERCP \n Pancreatitis") +
       geom_text(data = primary_outcome,
                 label = paste0(primary_outcome$percent*100,"%"),
                 nudge_y = 0.01) + 
       scale_fill_manual(values = c("#b9ceda","#256b81")) + 
       theme_classic() + 
       theme(legend.title = element_blank(),
             legend.position = "top",
             axis.title.y = element_text(face = "bold"),
             axis.title.x = element_text(face = "bold"),
             axis.text.x = element_blank(),
             axis.ticks.x = element_blank())

       
```



```{r}

# need to pull out some additional information
#focusing on primary end point and possible adverse events
```

