---
title: "R Notebook"
output: html_notebook
---



deicde on flex v shiny dashboard -- shny would be best but more $$$$?


```{r load data}
# ADDING TEST
# load data
library(medicaldata)

library(tidyverse)
library("kableExtra")

# this one looks good!
indo_rct <- medicaldata::indo_rct

```

# codebook
https://htmlpreview.github.io/?https://github.com/higgi13425/medicaldata/blob/master/man/codebooks/indo_rct_codebook.html

```{r}
# codebook
# https://htmlpreview.github.io/?https://github.com/higgi13425/medicaldata/blob/master/man/codebooks/indo_rct_codebook.html


#article related
#https://www.nejm.org/doi/full/10.1056/NEJMoa1111103



```


```{r}

head(indo_rct)

```



```{r}

# treatment group
indo_rct %>% group_by(rx) %>% count()

```




```{r age}


indo_rct %>% group_by(rx) %>% summarise(age_mean = round(mean(age),1),
                                        sd = round(sd(age),1))

```

```{r}


indo_rct %>% group_by(rx,gender) %>% count() %>% group_by(rx) %>%
             mutate(percent = round(n/sum(n),2)) 

```




```{r}

head(indo_rct)

```




```{r variables for table 1}
# sod - sphincter of oddi dysfunction was present, a risk factor favoring post-ERCP pancreatitis
# pep - previous post-ERCP pancreatitis (PEP), a risk factor for future PEP
# recpaesnc - Recurrent Pancreatitis, a risk factor for future PEP
# precut - a sphincter pre-cut was needed to enter the papilla, a risk factor for PEP
# difcan - Cannulation of the papilla was difficult, a risk factor for PEP
# amp - An Ampullectomy was performed for dysplasia or cancer, which could be a risk factor for PEP
# paninj - Contrast was injected into the pancreas during the procedure, a risk factor for PEP
# acinar - The pancreas appeared to have acinarization on imaging, which could be a risk factor for PEP
# prophystent - A pancreatic duct stent was placed at the end of the procedure per the judgement of the endoscopist (more often in high-risk cases), a potential protective effect against PEP
# bsphinct - A biliary sphincterotomy was performed, which could be a risk factor for PEP
#----bsphinc not bsinct

# train - A trainee participated in the ERCP, which could be a risk factor for PEP


# type - Sphincter of Oddi dysfunction type/level - higher numbers are more severe with greater association with PEP
indo_rct_long <- indo_rct %>% dplyr::select(id, site,rx, age, sod, pep,recpanc,precut,gender,type,sodsom,
                                            difcan,amp,train,prophystent,acinar,paninj,bsphinc,therastent) %>%
                 pivot_longer(cols = -c(id,site,rx,age),
                              names_to = "category", 
                              values_to = "value",
                              values_transform = list(value = as.character))
     

head(indo_rct_long)   
```









```{r table 1}

# still need to look for other variables

# thisi s the code for creating table 1, make into a nice kable?
# recreating table 1
table1_raw <- indo_rct_long %>% group_by(rx,category,value) %>% count() %>%
                  group_by(rx,category) %>%
                  # calculate percentages
                  mutate(percent =  round((n/sum(n))*100,1),
                         #total = sum(n),
                         #n_n = paste0(n,"/",total)
                         ) %>%
                  # only care about positives
                  filter(value %in% c("1_yes","1_female")) %>%
                  # remove uselss variables
                  dplyr::select(-value) %>%
                  ungroup() %>%
                  # pivot wider by treatment group
                  pivot_wider(., names_from = rx, values_from = n:percent) %>%
                  dplyr::select(category,
                                percent_0_placebo ,n_0_placebo,
                                percent_1_indomethacin,n_1_indomethacin)


table1_categorical <- table1_raw %>%
                  mutate(a_cat = 
                          case_when(
                            # reverse order at the moment
                             category == "train" ~ "Trainee involvement in ECRP",
                             category == "prophystent" ~ "Placement of Pancreatic Stent",
                             category == "amp" ~ "Ampullectomy",
                             category == "bsphinc" ~ "Theraputic Biliary Sphincterotomy",
                             category == "acinar" ~ "Pancreatic acinarisation",
                             category == "therastent" ~ "Therapeutic pancreatic schinterotomt",
                             category == "paninj" ~ "Pancreatography - Patients",
                             #"" ~ "Pancreatography - Median no. of injections of contrast agent into pancreatic duct",
                             category == "precut" ~ "Precut sphincterotomy",
                             category == "difcan" ~ "Difficult cannulation (> 8 attempts)",
                             category == "recpanc" ~ "History of recurrent pancreatitis",
                             category == "pep" ~ "History of post-ERCP pancreatitis",
                             category == "sodsom" ~ "Documented manometry",
                             category == "gender" ~ "Female sex",
                             TRUE ~ "999"),
                         cat_order = factor(category, levels = c("gender","sodsom","recpanc","difcan",
                                                                 "precut","paninj",
                                                                 "therastent","acinar",
                                                                 "bsphinc","amp",
                                                                 "prophystent","train")))



table1_categorical %>% arrange(cat_order)

#indo_rct_long %>% group_by(value) %>% count()

```


```{r}

# sphincter of oddi table

oddi_table <- indo_rct_long %>% filter(category == "type") %>% group_by(rx,category,value) %>% count() %>%
                  group_by(rx,category) %>%
                  # calculate percentages
                  mutate(percent =  round((n/sum(n))*100,1),
                         #total = sum(n),
                         #n_n = paste0(n,"/",total)
                         )

oddi_table_any <- indo_rct_long %>% filter(category == "type") %>%
                  mutate(value = ifelse(value == "0_no SOD","none","Any")) %>% 
                  group_by(rx,category,value) %>% count() %>%
                  group_by(rx,category) %>%
                  # calculate percentages
                  mutate(percent =  round((n/sum(n))*100,1),
                         #total = sum(n),
                         #n_n = paste0(n,"/",total)
                         ) %>%
                  filter(value == "Any") %>%
                  mutate(a_cat = case_when(category == "type" ~ "Clinical Definition of sphincter of Oddi dysfunction",
                                           TRUE ~ "999"))

oddi_table

```




```{r table 1 kable}


knitr::kable(table1,"html", table.attr = "style='width:80%;'",row.names = F,
      col.names = c("Characteristics","%","n","%","n"),
      align = c("l",rep("c",4))) %>%
      kable_styling(full_width = F,bootstrap_options = c("striped", "hover"), font_size = 10) %>%
      add_header_above(c(" " = 1, "Placebo" = 2, "Indomethacin" = 2))


```


































